### ISSUE TITLE
Better diagnostics for horserace

### ISSUE THREAD

**Issue by johansolbakken** [ThomasNitsche99/UltOrcs_v2#21]
Every action that the backend does in horserace should be recorded. 

There should be a "record" class or something that has fields: time, function_name, message and such. 

Then we can have a list in the game that displays the content of the diagnostics such that the players can see what has happened.

And if the developer needs to see all information, we can turn on a debug symbol which makes the list show function calls and such.

**Comment by ThomasNitsche99** [comment]
I Like the idea!
